---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
- bundle -v
- rm -f Gemfile.lock
- gem update --system
- gem --version
- bundle -v
script:
- 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
- 2.4.1
env:
  global:
  - BEAKER_PUPPET_COLLECTION=puppet5 PUPPET_GEM_VERSION="~> 5.0"
matrix:
  fast_finish: true
  include:
  - env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
  - env: CHECK=parallel_spec
  - env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
    rvm: 2.4.1
  - env: PUPPET_GEM_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
branches:
  only:
  - master
  - /^v\d/
  - /^\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: kobybr
  password:
    secure: "WQCvc2O+MV9k9ptIN+qbN9SIKRRvZAhbp+c/BhFHjS9Pe44PpHiHJiXP0zMM4O6gnNO2F2LASZK3lJePqlnrZOYYgIWOkA0Q+S7o859bBNMpOR9FxJEtfYFwq66oDZO+RS24Uw5a03peQ3mN9401KDSnsU/PB9+/NwJBkTzE+H5xN+pW3GJ5+7tc2JoAUE0tGOAxBhbmzrvhC9+HXXG+PuGzMs094e/ptqR/sxeY58SRTum7Iq3lg0ywPkR8ajyO8lI0JByPYv7vlKxfG08zt0IthEiizGjwRjnemdzuNVDwbMCCF7wNlzSM6bpXyAHMyp87gnuFNPn1QXTb06QjkeqbSRr0Mf/lTsK3gyIr3ArEDGQV5AYGBRUXbyVdaQDkoOC7jDtcCA6o+1g3ejh+BwM0h0ykbZjypo3kv0zbwiqekAj7lg63qG/feSQnnqwmK9SKDP6NCVO87a19t5N5IjWdbTqf7bvyKpq9HT4Mz6RlX9KUdMcxeguBvG1xN+S9h+S3Dxb/SSnglOI+HJo3taIe0IfjLkiArCdAId2mjkBs9sDPWU/Kjjn0ptzLByTsWVI5vP0m7ygjLqCYvcoTuHQAq5FLwWXQtKgi5XRCGzbU3btzEZ3LQFT8Pu5rRUo9I3bYCu0GtjjQJnhsYmOPy/SMv+1JzOgtM1BiNAIkv1s="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
